### ISSUE TITLE
how do you build custom functionality, is it a module? plugin

### ISSUE THREAD

**Issue by innvatehub** [usercode/DragonFly#1]
Hello this is wonderful, is there helper to create a module

- [ ] For e.g. if a developer was to create a Sports league or TimeEntry Module etc. what base classes does he need to create and wire up. A diagram on what components we need to implement there are manay generators from POCOs as well https://github.com/EasyAbp/AbpHelper.GUI
- [ ] Are these modules or plugins?
- [ ] Are roles and claims in the UI
- [ ] Themes - is there an easy way to add new themes BS 5
- [ ] Is there a drag drop page and dashboard builder 

Also are you planning a marketplace for listing sharing modules?

**Comment by usercode** [comment]
You should try Orchard or Umbraco.

DragonFly is just focused on content.
